### ISSUE TITLE
source / info re: resolve-node.now.sh dependency

### ISSUE THREAD

**Issue by knksmith57** [zeit/install-node.now.sh#2]
While tumbling through the internet, I noticed that the installer produced by this handler [relies on a now.sh deployment](https://github.com/zeit/install-node.now.sh/blob/2f845daf6c/install.sh#L91) ([resolve-node.now.sh](https://resolve-node.now.sh)) to resolve arbitrary tags to node releases.

I can't find the source for _that_ deployment anywhere (it's not public) and google / twitter / github / etc etc are all coming up empty.

Given y'all must have known about that deployment while building this installer, I'm wondering if you know anything about who owns / maintains it?

Thanks for taking a look!

/cc @TooTallNate

**Comment by TooTallNate** [comment]
Hey there Kyle, sorry for the late response. Somehow that source code as sitting on my local machine as was never pushed to GitHub, haha. I've pushed it now and it's located at https://github.com/zeit/resolve-node.now.sh. Pretty basic app, nothing too special. Thanks for the nudge though! OSS ftw 😄
